// Generated by CoffeeScript 1.4.0
var DEBUG, Game, Hero, Level, game;

Level = require('./level');

Hero = require('./units/hero');

DEBUG = true;

Game = (function() {

  function Game() {
    this.setupLevel();
    this.addHero();
  }

  Game.prototype.setupLevel = function() {
    this.level = new Level(100, 25);
    if (DEBUG) {
      return console.log(this.level.toString());
    }
  };

  Game.prototype.addHero = function() {
    var heroPos;
    heroPos = this.level.getRandomSpawnPos();
    this.hero = new Hero(15, "Hero", {
      x: 15,
      y: 20
    });
    return this.level.addHero(this.hero);
  };

  return Game;

})();

module.exports = Game;

if (DEBUG) {
  game = new Game();
}
