// Generated by CoffeeScript 1.4.0
var Generator;

Generator = (function() {

  function Generator(sizeX, sizeY) {
    this.sizeX = sizeX;
    this.sizeY = sizeY;
    this.initMap();
  }

  Generator.prototype.initMap = function() {
    var _this = this;
    console.log("Creating Level " + this.sizeX + "x" + this.sizeY);
    this.map = {};
    this.forTiles(function(tile, x, y) {
      if (x === 0 || x === _this.sizeX - 1 || y === 0 || y === _this.sizeY - 1) {
        return _this.setTile(x, y, TILE_TYPE.WALL);
      } else {
        return _this.setTile(x, y, TILE_TYPE.INVALID);
      }
    });
    this.generateRooms();
    return this.generateTunnels();
  };

  Generator.prototype.generate = function() {};

  return Generator;

})();

module.exports = Generator;
