// Generated by CoffeeScript 1.4.0
var Hero, Unit,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Unit = require('./unit');

Hero = (function(_super) {

  __extends(Hero, _super);

  function Hero(hp, name, pos) {
    this["super"](hp, name, pos);
  }

  return Hero;

})(Unit);

module.exports = Hero;
