// Generated by CoffeeScript 1.4.0
var Monster, Unit,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Unit = require('./unit');

Monster = (function(_super) {

  __extends(Monster, _super);

  function Monster(hp, name, pos) {
    this["super"](hp, name, pos);
  }

  return Monster;

})(Unit);

module.exports = Monster;
