// Generated by CoffeeScript 1.4.0
var Monster, Rat,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Monster = require('./monster');

Rat = (function(_super) {

  __extends(Rat, _super);

  function Rat(pos) {
    this["super"](5, "Rat", pos);
  }

  Rat.prototype.randomAttackDamage = function() {
    return Math.round(Math.max(Math.random() * 5, 1));
  };

  return Rat;

})(Monster);

module.exports = Rat;
