// Generated by CoffeeScript 1.4.0
var Unit;

Unit = (function() {

  function Unit(hp, name, pos) {
    this.hp = hp;
    this.name = name;
    this.pos = pos;
    this.target = null;
  }

  Unit.prototype.moveTo = function(pos, y) {
    if (y) {
      return this.pos = {
        x: pos,
        y: y
      };
    } else {
      return this.pos = pos;
    }
  };

  Unit.prototype.setTarget = function(target) {
    this.target = target;
  };

  Unit.prototype.target = function() {
    return this.target;
  };

  Unit.prototype.attack = function(target) {
    var damage;
    if (!target) {
      target = this.target;
    }
    damage = this.randomAttackDamage();
    this.onAttack(target, damage);
    return target.onAttacked(this, damage);
  };

  Unit.prototype.randomAttackDamage = function() {
    return 1;
  };

  Unit.prototype.onAttacked = function(attacker, damage, damageType) {
    if (damageType == null) {
      damageType = 'attacked';
    }
    console.log("" + attacker + " " + damageType + " you for " + damage + " health.");
    return this.hp -= damage;
  };

  Unit.prototype.onAttack = function(target, damage, damageType) {
    if (damageType == null) {
      damageType = 'attacked';
    }
    return console.log("You " + damageType + " " + attacker + " for " + damage + " health.");
  };

  return Unit;

})();

module.exports = Unit;
